### PR TITLE
Update Catch2 version to fix build error with recent glibc versions

### PR DESCRIPTION
**Pull request by darkerbit**
Recent glibc versions (appears to be 2.34) made `MINSIGSTKSZ` non-constant, which broke Catch2. This has been fixed in the most recent Catch2 release, however TrenchBroom and Vecmath are out of date and thus do not build with recent glibc versions, such as that used in Fedora Rawhide and Arch Linux.

This pull request simply updates the used Catch2 version to fix this. I have verified that this now builds on Arch Linux which was affected by the problem.

Related: catchorg/Catch2#2178 gabime/spdlog#1899 puppetlabs/cpp-hocon#132

Note: This pull request applies for both vecmath and TrenchBroom, and will be posted for both.

TrenchBroom PR: TrenchBroom/TrenchBroom#3958

### CODE REVIEW

**Comment by kduske** [comment]
Thanks for this! Could you rebase this branch onto master? I have fixed the formatting issues that fail in this PR.

**Comment by kduske** [comment]
That was fast. Thank you!

**Comment by darkerbit** [comment]
Alright, rebased it.

**Comment by eGax** [comment]
Thank you so much.

**Pull request merged**
